"""temp removal

Revision ID: 213d3ea72596
Revises: 796950eba885
Create Date: 2023-10-24 13:16:25.729447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '213d3ea72596'
down_revision = '796950eba885'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_constraint('fk_item_subroom_id_subroom', type_='foreignkey')
        batch_op.drop_column('subroom_id')

    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_constraint('fk_room_home_id_home', type_='foreignkey')
        batch_op.drop_column('home_id')

    with op.batch_alter_table('subroom', schema=None) as batch_op:
        batch_op.drop_constraint('fk_subroom_room_id_room', type_='foreignkey')
        batch_op.drop_column('room_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subroom', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fk_subroom_room_id_room', 'room', ['room_id'], ['id'])

    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fk_room_home_id_home', 'home', ['home_id'], ['id'])

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subroom_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fk_item_subroom_id_subroom', 'subroom', ['subroom_id'], ['id'])

    # ### end Alembic commands ###
