"""adding m2m join for room

Revision ID: 4a3fac3c2326
Revises: b8a10c96177e
Create Date: 2023-10-31 16:22:58.522844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a3fac3c2326'
down_revision = 'b8a10c96177e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_subroom',
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('subroom_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], name=op.f('fk_room_subroom_room_id_room')),
    sa.ForeignKeyConstraint(['subroom_id'], ['subroom.id'], name=op.f('fk_room_subroom_subroom_id_subroom'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room_subroom')
    # ### end Alembic commands ###
