"""add order

Revision ID: 5d14dda0c224
Revises: 41f1aa39c23b
Create Date: 2023-11-06 14:11:29.526647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d14dda0c224'
down_revision = '41f1aa39c23b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=True))

    with op.batch_alter_table('room_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room_items', schema=None) as batch_op:
        batch_op.drop_column('order')

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('order')

    # ### end Alembic commands ###
