"""starting items table

Revision ID: a771346967a3
Revises: 4a3fac3c2326
Create Date: 2023-11-01 11:37:35.954323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a771346967a3'
down_revision = '4a3fac3c2326'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    item_type_enum = sa.Enum('HOUSEHOLD', 'DECORATION', 'TOOL', 'UTENSIL', 'APPLIANCE',
                             'PHOTO', 'PERSONAL', 'ELECTRONIC', 'CLOTHING', 'PET', 'MISCELLANEOUS', name='itemtype')
    item_type_enum.create(op.get_bind(), checkfirst=False)
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('description', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('item_type', sa.Enum('HOUSEHOLD', 'DECORATION', 'TOOL', 'UTENSIL', 'APPLIANCE',
                            'PHOTO', 'PERSONAL', 'ELECTRONIC', 'CLOTHING', 'PET', 'MISCELLANEOUS', name='itemtype'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('item_type')
        batch_op.drop_column('description')
    item_type_enum = sa.Enum('HOUSEHOLD', 'DECORATION', 'TOOL', 'UTENSIL', 'APPLIANCE',
                             'PHOTO', 'PERSONAL', 'ELECTRONIC', 'CLOTHING', 'PET', 'MISCELLANEOUS', name='itemtype')
    item_type_enum.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
