"""add rooms to home

Revision ID: b8a10c96177e
Revises: db1be46a3d9f
Create Date: 2023-10-31 11:33:45.167453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8a10c96177e'
down_revision = 'db1be46a3d9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    room_type_enum = sa.Enum('BEDROOM', 'BATHROOM', 'GARAGE',
                             'KITCHEN', 'LIVING_ROOM', 'ATTIC', name='roomtype')
    room_type_enum.create(op.get_bind(), checkfirst=False)

    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('description', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('room_type', sa.Enum(
            'BEDROOM', 'BATHROOM', 'GARAGE', 'KITCHEN', 'LIVING_ROOM', 'ATTIC', name='roomtype'), nullable=False))
        batch_op.add_column(sa.Column('home_id', sa.Integer(), nullable=False))
        batch_op.alter_column('name',
                              existing_type=sa.VARCHAR(length=128),
                              nullable=False)
        batch_op.create_foreign_key(batch_op.f(
            'fk_room_home_id_homes'), 'homes', ['home_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_home_id_homes', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_user_home_id_homes'), 'homes', [
                                    'home_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f(
            'fk_user_home_id_homes'), type_='foreignkey')
        batch_op.create_foreign_key(
            'fk_user_home_id_homes', 'homes', ['home_id'], ['id'])

    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f(
            'fk_room_home_id_homes'), type_='foreignkey')
        batch_op.alter_column('name',
                              existing_type=sa.VARCHAR(length=128),
                              nullable=True)
        batch_op.drop_column('home_id')
        batch_op.drop_column('room_type')
        batch_op.drop_column('description')
    room_type_enum = sa.Enum('BEDROOM', 'BATHROOM', 'GARAGE',
                             'KITCHEN', 'LIVING_ROOM', 'ATTIC', name='roomtype')
    room_type_enum.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
