"""join items table

Revision ID: fd3cf7175001
Revises: a771346967a3
Create Date: 2023-11-01 11:53:57.869854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd3cf7175001'
down_revision = 'a771346967a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('subroom_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('(room_id IS NOT NULL AND subroom_id IS NULL) OR (room_id IS NULL AND subroom_id IS NOT NULL)', name='check_single_location_for_item'),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name=op.f('fk_room_items_item_id_item')),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], name=op.f('fk_room_items_room_id_room')),
    sa.ForeignKeyConstraint(['subroom_id'], ['subroom.id'], name=op.f('fk_room_items_subroom_id_subroom')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room_items')
    # ### end Alembic commands ###
